[package]
name = "cairo_contracts"
version = "0.2.0"
authors = ["Satyam Bansal <satyamsgsits1994@gmail.com>"]
description = "Collection of commonly used starknet smart contracts"
readme = "README.md"
repository = "https://github.com/satyambnsal/cairo-smart-contracts"
license = "MIT"
keywords = ["Cairo", "Starknet", "Layer2"]

[dependencies]
# foo = { path = "vendor/foo" }
starknet = ">=2.1.0"
# alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "cairo-v2.1.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.8.1" }

# comment following line if executing non-starknet cairo programs
[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"


[tool.snforge]
exit_first = true

[tool.sncast.localaccount1]
account = "/Users/satyam/.starkli-wallets/deployer/my_local_account_2.json"
keystore-file = "/Users/satyam/.starkli-wallets/deployer/my_local_account_2_key.json"
url = "http://127.0.0.1:5050/"

[tool.sncast.testnet]
account = "/Users/satyam/.starkli-wallets/deployer/my_testnet_account_1.json"
keystore-file = "/Users/satyam/.starkli-wallets/deployer/my_testnet_account_1_key.json"
url = "https://starknet-goerli.infura.io/v3/0ae9d2edafaa4ab3af19c4600b93fd0a"
